### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lamaland** [getbigger-io/prisma-fixtures#1]
Hi :)

thanks for working on this, very useful!

I have a problem with date formating using faker, it seems that a "toString" method is called in the fakerParser, which leads to a very stange behavior.

Is this the expected result?

![image](https://user-images.githubusercontent.com/42850368/105172889-8e55c980-5b20-11eb-8d6a-8871ef5e5865.png)
![image](https://user-images.githubusercontent.com/42850368/105172795-6ebea100-5b20-11eb-9bab-db027ddb0e8b.png)

**Comment by nmacherey** [comment]
Hi @lamaland !  It seams that the faker.fake method is returning a string instead of a date instance. 
I will try to find a fix

**Comment by nmacherey** [comment]
should be fixed in 1.0.9.
reqgards

**Comment by lamaland** [comment]
thank you @nmacherey :)
