### ISSUE TITLE
[Feature request] Upgrading faker version

### ISSUE THREAD

**Issue by lamaland** [getbigger-io/prisma-fixtures#5]
Hi,

Just pushed a [merge request](https://github.com/getbigger-io/prisma-fixtures/pull/4) to upgrade faker-js version to 7.x.

Thanks for this awesome lib :)

**Comment by lamaland** [comment]
Broken pipeline :(
https://github.com/getbigger-io/prisma-fixtures/pull/6

**Comment by lamaland** [comment]
@nmacherey Do you have any plan for a new package release? (Just to know, don't worry, I have workarounds)
Thanks :pray:

**Comment by nmacherey** [comment]
@lamaland  the master is up to date now.
I am planning to do some additional testing tomorrow and a new release on friday

**Comment by lamaland** [comment]
Thank you :)

**Comment by lamaland** [comment]
I've been hardly testing faker's new features on the master in my project.
No issue found at the moment, nice! :+1:

**Comment by lamaland** [comment]
Thanks for the release !

**Comment by nmacherey** [comment]
Yes this week

Envoyé de mon iPhone

**Comment by cryptiklemur** [comment]
Can you upgrade again?
